### ISSUE TITLE
Is it possible to supply dynamic key parameters in bootconfig.xml file (Android) or the bootconfig.plist file (iOS) ??

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-Templates#311]
Hi Team,

We have requirement to connect single reactNative SDK app to different Salesforce instances like Global or Regional orgs. Both orgs are having different connected apps and its keys. Is it possible to use single mobile SDK app  to target different Salesforce orgs via bootconfig?

Best Regards,
-Vivekanand Deshmane

**Comment by bhariharan** [comment]
A few comments:
- For your use case, you don't need multiple connected apps, you can use the same connected app. Connected apps are installed across all orgs, so you can use the same `consumerKey` and `callbackUrl`.
- By design, a mobile app should have only 1 connected app it's associated with. This is by design, and allows admins to control policies for that mobile app.
- So, with a Mobile SDK app, you can not connect to multiple connected apps at runtime, and this is by design.

Please post any general queries on `Stack Exchange`. This forum is reserved for bugs/issues with our code.
